"""Add SiteContent model

Revision ID: 508997bfc31e
Revises: d024a2232775
Create Date: 2026-07-19 23:45:49.378311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508997bfc31e'
down_revision = 'd024a2232775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_content_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_content_key'))

    op.drop_table('site_content')
    # ### end Alembic commands ###
