"""Expanded university model and added scholarship, faq, placement partner models

Revision ID: 50c1645486e8
Revises: f1e96a4a8cb2
Create Date: 2026-07-13 13:21:45.284132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c1645486e8'
down_revision = 'f1e96a4a8cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faqs_university_id'), ['university_id'], unique=False)

    op.create_table('placement_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('placement_partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_partners_university_id'), ['university_id'], unique=False)

    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deadline', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scholarships_university_id'), ['university_id'], unique=False)

    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('banner_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('brochure_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('full_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('why_choose', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ownership', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('university_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ugc_approved', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('aicte_approved', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('aiu_member', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('wes_approved', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('placement_support', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('highest_package', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('average_package', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('top_recruiters', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_students', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('faculty_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alumni_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=320), nullable=True))
        batch_op.add_column(sa.Column('gallery_images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_column('gallery_images')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('alumni_count')
        batch_op.drop_column('faculty_count')
        batch_op.drop_column('total_students')
        batch_op.drop_column('top_recruiters')
        batch_op.drop_column('average_package')
        batch_op.drop_column('highest_package')
        batch_op.drop_column('placement_support')
        batch_op.drop_column('wes_approved')
        batch_op.drop_column('aiu_member')
        batch_op.drop_column('aicte_approved')
        batch_op.drop_column('ugc_approved')
        batch_op.drop_column('university_type')
        batch_op.drop_column('ownership')
        batch_op.drop_column('why_choose')
        batch_op.drop_column('full_description')
        batch_op.drop_column('short_description')
        batch_op.drop_column('brochure_url')
        batch_op.drop_column('banner_url')
        batch_op.drop_column('logo_url')

    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scholarships_university_id'))

    op.drop_table('scholarships')
    with op.batch_alter_table('placement_partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_partners_university_id'))

    op.drop_table('placement_partners')
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faqs_university_id'))

    op.drop_table('faqs')
    # ### end Alembic commands ###
