"""Add role column

Revision ID: d024a2232775
Revises: 50c1645486e8
Create Date: 2026-07-14 23:16:00.900631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd024a2232775'
down_revision = '50c1645486e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compare_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university_ids', sa.String(length=100), nullable=False),
    sa.Column('university_names', sa.Text(), nullable=True),
    sa.Column('compared_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compare_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compare_history_compared_at'), ['compared_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compare_history_user_id'), ['user_id'], unique=False)

    op.create_table('saved_universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'university_id', name='uq_saved_university')
    )
    with op.batch_alter_table('saved_universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_universities_university_id'), ['university_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_universities_user_id'), ['user_id'], unique=False)

    op.create_table('brochure_downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brochure_downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brochure_downloads_downloaded_at'), ['downloaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brochure_downloads_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brochure_downloads_university_id'), ['university_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brochure_downloads_user_id'), ['user_id'], unique=False)

    op.create_table('recently_viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recently_viewed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recently_viewed_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recently_viewed_university_id'), ['university_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recently_viewed_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recently_viewed_viewed_at'), ['viewed_at'], unique=False)

    op.create_table('saved_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'program_id', name='uq_saved_program')
    )
    with op.batch_alter_table('saved_programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_programs_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_programs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='student', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('saved_programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_programs_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_programs_program_id'))

    op.drop_table('saved_programs')
    with op.batch_alter_table('recently_viewed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recently_viewed_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_recently_viewed_user_id'))
        batch_op.drop_index(batch_op.f('ix_recently_viewed_university_id'))
        batch_op.drop_index(batch_op.f('ix_recently_viewed_program_id'))

    op.drop_table('recently_viewed')
    with op.batch_alter_table('brochure_downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brochure_downloads_user_id'))
        batch_op.drop_index(batch_op.f('ix_brochure_downloads_university_id'))
        batch_op.drop_index(batch_op.f('ix_brochure_downloads_program_id'))
        batch_op.drop_index(batch_op.f('ix_brochure_downloads_downloaded_at'))

    op.drop_table('brochure_downloads')
    with op.batch_alter_table('saved_universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_universities_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_universities_university_id'))

    op.drop_table('saved_universities')
    with op.batch_alter_table('compare_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compare_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_compare_history_compared_at'))

    op.drop_table('compare_history')
    # ### end Alembic commands ###
